project:
  type: website
  output-dir: docs

website:
  title: "Junye's Website"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: resume.qmd
        text: Resume
      - href: HW1/hw1_questions.qmd
        text: HW1

# format:
#   html:
#     theme:
#       - cosmo
#       - brand
#     css: styles.css
#     toc: true

format:
  html:
    toc: true
    toc-depth: 2
    number-sections: false



